platforms = [ "string" ]
provides = [ "ref = 'format.pep508-identifier'" ]
obsoletes = [ "ref = 'format.pep508-identifier'" ]
zip-safe = "boolean"
script-files = [ "string" ]
eager-resources = [ "string" ]
packages = { "union = 'one'" = [
    [ "ref = 'defs.package-name'" ],
    "ref = 'defs.find-directive'",
] }
include-package-data = "boolean"
namespace-packages = [ "ref = 'format.python-module-name-relaxed'" ]
py-modules = [ "ref = 'format.python-module-name-relaxed'" ]
ext-modules = [ "ref = 'defs.ext-module'" ]
license-files = [ "string" ]

[package-dir]
"pattern = '^.*$'" = "string"

[package-data]
"pattern = '^.*$'" = [ "string" ]

[exclude-package-data]
"pattern = '^.*$'" = [ "string" ]

[data-files]
"pattern = '^.*$'" = [ "string" ]
"*" = "any-value"

[cmdclass]
"pattern = '^.*$'" = "ref = 'format.python-qualified-identifier'"
"*" = "any-value"

[dynamic]
version = { "union = 'one'" = [
    "ref = 'defs.attr-directive'",
    "ref = 'defs.file-directive'",
] }
classifiers = "ref = 'defs.file-directive'"
description = "ref = 'defs.file-directive'"
entry-points = "ref = 'defs.file-directive'"
dependencies = "ref = 'defs.file-directive-for-dependencies'"
readme = { union = [
    "ref = 'defs.file-directive'",
    { content-type = "string", "file = { required = true }" = "ref = 'defs.file-directive.file'" },
] }

[dynamic.optional-dependencies]
"pattern = '.+'" = "ref = 'defs.file-directive-for-dependencies'"

["defs = { hidden = true }"]
package-name = { union = [
    "ref = 'format.python-module-name-relaxed'",
    "ref = 'format.pep561-stub-name'",
] }
file-directive-for-dependencies = "ref = 'defs.file-directive'"

["defs = { hidden = true }".ext-module]
"name = { required = true }" = "ref = 'format.python-module-name-relaxed'"
"sources = { required = true }" = [ "string" ]
include-dirs = [ "string" ]
define-macros = [ [ "string", "min-items = 2", "max-items = 2" ] ]
undef-macros = [ "string" ]
library-dirs = [ "string" ]
libraries = [ "string" ]
runtime-library-dirs = [ "string" ]
extra-objects = [ "string" ]
extra-compile-args = [ "string" ]
extra-link-args = [ "string" ]
export-symbols = [ "string" ]
swig-opts = [ "string" ]
depends = [ "string" ]
language = "string"
optional = "boolean"
py-limited-api = "boolean"

["defs = { hidden = true }".file-directive]
"file = { required = true }" = { union = [
    "string",
    [ "string" ],
] }

["defs = { hidden = true }".attr-directive]
"attr = { required = true }" = "ref = 'format.python-qualified-identifier'"

["defs = { hidden = true }".find-directive]

["defs = { hidden = true }".find-directive.find]
where = [ "string" ]
exclude = [ "string" ]
include = [ "string" ]
namespaces = "boolean"

["format = { hidden = true }"]

pep508-identifier = "pattern = '^.*$'"

python-module-name-relaxed = "pattern = '^.*$'"

python-qualified-identifier = "pattern = '^.*$'"

pep561-stub-name = "pattern = '^.*$'"
