settings = "ref = 'defs.Settings'"

[tasks]
"pattern = '^.+$'" = "ref = 'defs.Task'"

[variables]
"pattern = '^[0-9a-zA-Z]+$'" = [
    "union",
    "ref = 'defs.VariableValue'",
    "ref = 'defs.Variable'",
]

["defs = { hidden = true }"]
Task = [
    "union",
    "ref = 'defs.Command'",
    { "cmd = { required = true }" = "ref = 'defs.Command'", help = "string = { min-len = 1 }", use_vars = "ref = 'defs.UseVars'", cwd = "ref = 'defs.Cwd'", "*" = "any-value" },
]
Command = "string = { min-len = 1 }"
VariableValue = "string = { min-len = 1 }"
UseVars = "boolean"
Cwd = "string = { min-len = 1 }"

["defs = { hidden = true }".Variable]
var = "ref = 'defs.VariableValue'"
recursive = "boolean"
"*" = "any-value"

["defs = { hidden = true }".Settings]
use_vars = "ref = 'defs.UseVars'"
cwd = "ref = 'defs.Cwd'"
