select = "ref = 'defs.checks'"
ignore = { "union = 'one'" = [
    "ref = 'defs.checks'",
    { "pattern = '^[A-Z]+[0-9]*$'" = "string" },
] }

["defs = { hidden = true }"]
checks = [ """
    pattern = '^[A-Z]+[0-9]*$'
""" ]
