platforms = [ "string" ]
provides = [ "string" ]
obsoletes = [ "string" ]
zip-safe = "boolean"
script-files = [ "string" ]
eager-resources = [ "string" ]
packages = [
    "union",
    [ "ref = 'defs.package-name'" ],
    "ref = 'defs.find-directive'",
]
include-package-data = "boolean"
namespace-packages = [ "string" ]
py-modules = [ "string" ]
ext-modules = [ "ref = 'defs.ext-module'" ]
license-files = [ "string" ]

[package-dir]
"pattern = '^.*$'" = "string"

[package-data]
"pattern = '^.*$'" = [ "string" ]

[exclude-package-data]
"pattern = '^.*$'" = [ "string" ]

[data-files]
"pattern = '^.*$'" = [ "string" ]
"*" = "any-value"

[cmdclass]
"pattern = '^.*$'" = "string"
"*" = "any-value"

[dynamic]
version = [
    "union",
    "ref = 'defs.attr-directive'",
    "ref = 'defs.file-directive'",
]
classifiers = "ref = 'defs.file-directive'"
description = "ref = 'defs.file-directive'"
entry-points = "ref = 'defs.file-directive'"
dependencies = "ref = 'defs.file-directive-for-dependencies'"
readme = [
    "union",
    "ref = 'defs.file-directive'",
    { content-type = "string", "file = { required = true }" = "ref = 'defs.file-directive.file'" },
]

[dynamic.optional-dependencies]
"pattern = '.+'" = "ref = 'defs.file-directive-for-dependencies'"

["defs = { hidden = true }"]
package-name = "string"
file-directive-for-dependencies = [
    "union",
    { },
    "ref = 'defs.file-directive'",
]

["defs = { hidden = true }".ext-module]
"name = { required = true }" = "string"
"sources = { required = true }" = [ "string" ]
include-dirs = [ "string" ]
define-macros = [ [ { } ] ]
undef-macros = [ "string" ]
library-dirs = [ "string" ]
libraries = [ "string" ]
runtime-library-dirs = [ "string" ]
extra-objects = [ "string" ]
extra-compile-args = [ "string" ]
extra-link-args = [ "string" ]
export-symbols = [ "string" ]
swig-opts = [ "string" ]
depends = [ "string" ]
language = "string"
optional = "boolean"
py-limited-api = "boolean"

["defs = { hidden = true }".file-directive]
"file = { required = true }" = [
    "union",
    "string",
    [ "string" ],
]

["defs = { hidden = true }".attr-directive]
"attr = { required = true }" = "string"

["defs = { hidden = true }".find-directive]

["defs = { hidden = true }".find-directive.find]
where = [ "string" ]
exclude = [ "string" ]
include = [ "string" ]
namespaces = "boolean"
