[project]
name = "some-project"
author = { name = "Anderson Bravalheri" }
description = "Some description"
readme = "README.rst"
license = {}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Utilities",
]
dynamic = ["version"]
requires-python = ">=3.6"
dependencies = [
    "importlib-metadata; python_version<\"3.8\"",
    "appdirs>=1.4.4,<2",
]

[tool.setuptools]
zip-safe = false
include-package-data = true
exclude-package-data = { "pkg1" = ["*.yaml"] }
package-dir = {"" = "src"} # all the packages under the src folder
platforms = ["any"]

[tool.setuptools.packages]
find = { where = ["src"], exclude = ["tests"], namespaces = true }
